#This master script handles the pipeline for analyzing the predictive capacity of DFEs as a function of time in the LTEE. It requires the presence in this folder of the files Rtoanal.dat, Ttoanal.dat, Ftoanal.dat generated by 'barplots_ben.R' in folder '3. DFE analyses'.

# .. remove any previous content in the session
rm(list=ls())

# .. estimate representativity of actual DFEs
source('representativeness_real.R')

# .. create control DFEs by random sampling an equivalent number of loci
source('neutrality.R')

# .. estimate representativity of simulated data
source('representativeness_sim.R')

# .. plot the analyses
source('predicting.R')
